import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Yamme Tee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          padding: 0,
          height: "100vh",
          width: "100vw",
          backgroundColor: "#0a0a0a",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          overflow: "hidden",
          fontFamily: "'Zalando Sans SemiExpanded', sans-serif",
          color: "#ffffff",
        }}
      >
        {/* Подключение Google Font */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Zalando+Sans+SemiExpanded:ital,wght@0,200..900;1,200..900&display=swap"
          rel="stylesheet"
        />

        <h1 className="flicker">Yamme Tee was here...</h1>

        <style>{`
          h1.flicker {
            font-size: 1em;
            font-weight: 400;
            text-align: center;
            line-height: 1.1;
            animation: flickerAnimation 2s infinite;
          }

          @keyframes flickerAnimation {
            0%   { opacity: 1; }
            10%  { opacity: 0.1; }
            20%  { opacity: 0.8; }
            30%  { opacity: 0.2; }
            40%  { opacity: 1; }
            50%  { opacity: 0.3; }
            60%  { opacity: 1; }
            70%  { opacity: 0.2; }
            80%  { opacity: 0.9; }
            90%  { opacity: 0.1; }
            100% { opacity: 1; }
          }

          /* Адаптивность для мобильных */
          @media (max-width: 600px) {
            h1.flicker {
              font-size: 1em;
            }
          }
        `}</style>

        {children}
      </body>
    </html>
  );
}
