import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Yamme Tee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          padding: 0,
          height: "100%",
          width: "100%",
          backgroundColor: "#0a0a0a",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          fontFamily: "'Bangers', cursive",
          color: "#ff6f61",
          textAlign: "center",
        }}
      >
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&display=swap"
          rel="stylesheet"
        />
        <h1
          style={{
            fontSize: "8vw",
            textShadow: "2px 2px 8px rgba(0,0,0,0.6)",
          }}
        >
          Yamme Tee was here...
        </h1>
        {children}
      </body>
    </html>
  );
}
